import Foundation

/// The offline dictionary: the app's single source for the daily-word pool, word validity, and word
/// meanings — all served from the bundled `dictionary.json` (generated by `tools/build_wordlist.py`,
/// see `tools/PROVENANCE.md`). This replaces both the old `common.json` word source and the network
/// meaning lookup, so the whole game — gameplay *and* meanings — is fully offline.
///
/// Class-bound and registered `.container` (one shared instance, `===` in `DependencyGraphTests`): the
/// bundle is decoded once at launch into in-memory collections and read by both the word provider and
/// the dictionary repository.
protocol WordDatabaseType: AnyObject {
    /// The pool of fair, singular, defined words eligible to be a day's word.
    func answerWords() -> [String]
    /// Whether `word` is a legitimate 5-letter word (the broad VALID set, a superset of the answers).
    func isValid(_ word: String) -> Bool
    /// The offline meaning for `word`, or `nil` if the bundle carries no definition for it.
    func meaning(for word: String) -> WordMeaningModel?
}

final class WordDatabase: WordDatabaseType {

    // MARK: - Life Cycle

    init(resourceLoader: ResourceLoaderType, decoder: DecoderType) {
        do {
            let data = try resourceLoader.loadResource(named: "dictionary", withExtension: "json")
            let entity = try decoder.decode(WordDatabaseEntity.self, from: data)
            self.answers = entity.answers
            self.validWords = Set(entity.valid)
            self.meanings = entity.definitions.reduce(into: [:]) { store, pair in
                store[pair.key] = WordMeaningModel(word: pair.key, entry: pair.value)
            }
        } catch {
            // The bundle is a shipped, generated asset — a decode failure is a build-time
            // integrity error, mirrored on the SwiftData `sharedModelContainer` fatalError.
            fatalError("Failed to load bundled dictionary.json: \(error)")
        }
    }

    // MARK: - Publics

    func answerWords() -> [String] { answers }

    func isValid(_ word: String) -> Bool { validWords.contains(word) }

    func meaning(for word: String) -> WordMeaningModel? { meanings[word] }

    // MARK: - Privates

    private let answers: [String]
    private let validWords: Set<String>
    private let meanings: [String: WordMeaningModel]
}

/// The on-disk shape of `dictionary.json`. Kept separate from the domain `WordMeaningModel` so the
/// bundle format can evolve independently of what the UI renders.
struct WordDatabaseEntity: Decodable, Equatable {
    let version: Int
    let answers: [String]
    let valid: [String]
    let definitions: [String: Definition]

    /// A word's full set of senses, grouped by part of speech (mirrors what the meaning
    /// screen's POS picker + numbered definitions render).
    struct Definition: Decodable, Equatable {
        let meanings: [Meaning]

        struct Meaning: Decodable, Equatable {
            let pos: String
            let definitions: [String]
        }
    }
}

private extension WordMeaningModel {
    init(word: String, entry: WordDatabaseEntity.Definition) {
        self.init(
            word: word,
            meanings: entry.meanings.map { meaning in
                Meaning(
                    partOfSpeech: Meaning.PartOfSpeech(rawValue: meaning.pos) ?? .noun,
                    definitions: meaning.definitions.map { Meaning.Definition(definition: $0) }
                )
            }
        )
    }
}
